package com.example.dllo.mirror.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.mirror.model.db.Users;
import com.example.dllo.mirror.model.db.Address;

import com.example.dllo.mirror.model.db.UsersDao;
import com.example.dllo.mirror.model.db.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final UsersDao usersDao;
    private final AddressDao addressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        usersDao = new UsersDao(usersDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(Users.class, usersDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        usersDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
