package com.example.dllo.mirror.model.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS".
 */
public class Users {

    private Long id;
    private String uid;
    private String token;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String uid, String token) {
        this.id = id;
        this.uid = uid;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

}
